# Generated by Django 4.1.4 on 2023-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
