# Generated by Django 4.1.4 on 2023-01-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Tech", "Tech"),
                    ("Health", "Health"),
                    ("Sports", "Sports"),
                    ("Business", "Business"),
                    ("Finance", "Finance"),
                    ("None", "None"),
                ],
                default="None",
                max_length=64,
            ),
        ),
    ]
