# Generated by Django 4.1.4 on 2023-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image_caption",
            field=models.TextField(null=True),
        ),
    ]
