# Generated by Django 4.1.4 on 2023-01-16 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_image_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="readtime",
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
